export const surveyResources = {
    survey_management_knowledge: {
        title: "Survey Management — Policies, Process & Best Practices",
        domain: "surveys",
        overview: "Comprehensive guidance on how post-delivery surveys are managed — when they open, how long they stay open, what happens when response rates are low, and how reopening works. This resource explains the end-to-end survey lifecycle from creation to closure.",
        whenThisApplies: "Use this resource when a Learning Advisor asks about survey policies, how surveys work, or best practices for maximizing response rates. For actual survey data retrieval or reopening, use the related tools.",
        keyRules: [
            "Surveys are automatically triggered at offering completion and sent to all enrolled participants.",
            "The standard survey window is 14 calendar days from trigger date.",
            "Response rate below 50% triggers an automatic reminder at the 7-day mark.",
            "If response rate is still below 50% at closure, the Learning Advisor is notified and may request a survey window extension.",
            "Survey reopening requires a formal request with a business justification.",
            "Survey data becomes available for reporting 24 hours after the survey window closes.",
            "Anonymous survey responses cannot be traced back to individual learners.",
        ],
        commonMisconceptions: [
            "Survey links are not the same as course feedback forms — surveys follow a standardized organizational template.",
            "Reopening a survey does not re-trigger notification emails — the Learning Advisor must manually share the link with participants.",
            "Survey results do not affect course completion status — surveys and completions are separate processes.",
        ],
        escalationPath: "For survey platform issues (link not working, responses not recording), escalate to the survey administration team. For low response rates, work with the course owner to send reminder communications.",
        relatedTools: ["reopen_survey_window", "get_survey_report", "amend_survey_closure"],
        exampleQuestions: [
            "How do surveys work?",
            "When do surveys go out?",
            "What is the standard survey window?",
            "How do I improve survey response rates?",
            "What happens if the survey response rate is too low?",
        ],
    },
    survey_closure_policy_knowledge: {
        title: "Survey Closure Policy & Amendments",
        domain: "surveys",
        overview: "Explains the standard survey closure timing, when amendments to closure dates are permitted, and the process for requesting exceptions. Covers both shortening and extending survey windows.",
        whenThisApplies: "Use this resource when a Learning Advisor asks about survey closure rules, whether closure dates can be changed, or what the standard closure timing is. For executing a closure amendment, use the amend_survey_closure tool.",
        keyRules: [
            "Standard closure is 14 calendar days after the survey trigger date.",
            "Early closure (e.g., from 14 days to 7 days) may be approved if the minimum response threshold (50%) is already met.",
            "Extension beyond 14 days requires justification (e.g., holiday period overlap, large cohort needing more time).",
            "Maximum extension is typically 30 days from trigger date — extensions beyond this require senior management approval.",
            "Closure date amendments do not affect already-submitted responses.",
        ],
        commonMisconceptions: [
            "Changing the closure date does not re-open the survey for people who already responded — they cannot submit again.",
            "The standard 14-day window is not negotiable for shortening without the 50% threshold being met.",
        ],
        relatedTools: ["amend_survey_closure", "get_survey_report"],
        exampleQuestions: [
            "Can survey closure dates be amended?",
            "What is the standard survey closure timing?",
            "When can exceptions be discussed for survey closure?",
            "Can we close the survey early if we have enough responses?",
        ],
    },
    express_interest_knowledge: {
        title: "Express Interest — How It Works",
        domain: "surveys",
        overview: "Explains the express interest mechanism — what it actually does, how it captures demand, and critically, what it does NOT do (it does not notify learners, confirm enrollment, or reserve seats).",
        whenThisApplies: "Use this resource when a Learning Advisor asks about how express interest works or has misconceptions about its behavior. For fetching express interest data, use the get_express_interest_report tool.",
        keyRules: [
            "Express interest is a demand capture mechanism — it records learner intent to attend a future course.",
            "It does NOT create an enrollment, reserve a seat, or trigger any notification to the learner.",
            "Express interest data is used by the planning team to inform go/no-go decisions and determine how many offerings to create.",
            "Learners are NOT notified when an offering is created based on their expressed interest — the Learning Advisor must manually communicate availability.",
            "Express interest data can be exported for analysis and planning purposes.",
        ],
        commonMisconceptions: [
            "Express interest does NOT notify learners — this is the #1 misconception.",
            "It does not guarantee the learner a seat when an offering is created.",
            "It does not equal enrollment — the learner must still go through the enrollment process.",
            "The data does not expire — old express interest records remain unless manually archived.",
        ],
        escalationPath: "No escalation needed — this is an informational resource. If the process needs to change (e.g., adding auto-notification), that is a product enhancement request to the LMS team.",
        relatedTools: ["get_express_interest_report"],
        exampleQuestions: [
            "How does express interest work?",
            "Does express interest notify learners?",
            "What does express interest actually do?",
            "Is express interest the same as enrollment?",
            "How is express interest data used for planning?",
        ],
    },
};
